### ISSUE TITLE
Add DD-WRT section?

### ISSUE THREAD

**Issue by ClashTheBunny** [pirate/wireguard-docs#11]
It would be nice to add one more server type in there:
https://wiki.dd-wrt.com/wiki/index.php/The_Easiest_Tunnel_Ever

**Comment by pirate** [comment]
Wasn't sure where the best place would be, so I added it here: https://github.com/pirate/wireguard-docs/commit/f776b0f9eee1a19d61d49ef1e919db8dab2ea107

Thanks!
