### ISSUE TITLE
Use documentation IPv4/6 addresses

### ISSUE THREAD

**Issue by titanofold** [pirate/wireguard-docs#12]
Rather than accidentally encouraging people to connect to random, possibly live IP addresses, we should use the addresses specifically set aside for the purpose of documentation.

[RFC3849](https://tools.ietf.org/html/rfc3849) states the following for IPv6:

> The prefix allocated for documentation purposes is **2001:DB8::/32**

[RFC5737](https://tools.ietf.org/html/rfc5737) states the following for IPv4:

> The blocks **192.0.2.0/24** (TEST-NET-1), **198.51.100.0/24** (TEST-NET-2), and **203.0.113.0/24** (TEST-NET-3) are provided for use in documentation.

Obviously, using internal addresses (192.168.0.0/16, 172.16.0.0/12, 10.0.0.0/8, fc00::/7) as examples for internal IPs are fine as they'll never reach outside the internal network...allegedly.

**Comment by pirate** [comment]
Done https://github.com/pirate/wireguard-docs/commit/889d8a29cfb4ebbb5048318ac051fc0e959e10a6. Thanks!
