### ISSUE TITLE
Things to add

### ISSUE THREAD

**Issue by joachimlindenberg** [pirate/wireguard-docs#18]
you may want to add SSTP. I like SSTP because for most network equipment it looks like a standard https connection, and therefore it works in almost any hotel or business network , whether it uses a firewall or captive portal. It is also very easy to use and configure on Windows clients.
SoftEther (among other protocols) implements an open source SSTP server.

**Comment by pirate** [comment]
Another one to add: https://github.com/jedisct1/dsvpn

**Comment by pirate** [comment]
https://github.com/wg-dashboard/wg-dashboard

**Comment by daluf** [comment]
@pirate wg-dashboard added in #20 :)

**Comment by pirate** [comment]
Closed by #26
