### ISSUE TITLE
Adding Automated Script

### ISSUE THREAD

**Issue by ThePigPeppa** [pirate/wireguard-docs#22]
**Automated Script:**

```
https://github.com/complexorganizations/wireguard-install
```

Maybe adding this on the README.md

@pirate

**Comment by pirate** [comment]
If you submit a PR to add it where you think is best, I'll merge it.

**Comment by ThePigPeppa** [comment]
@pirate Thanks.
https://github.com/pirate/wireguard-docs/pull/23
