### ISSUE TITLE
Please add VpnCloud to your "List of Possible VPN Solutions"

### ISSUE THREAD

**Issue by bmullan** [pirate/wireguard-docs#25]
I think you ought to add **VpnCloud** to your [List of Possible VPN Solutions](https://github.com/pirate/wireguard-docs#List-of-Possible-VPN-Solutions).

I've  found VpnCloud quite good so far for Full-Mesh, Auto-Learning VPN.
Its extremely easy to configure for Server/Hosts & Peers.

https://vpncloud.ddswd.de/features/
https://vpncloud.ddswd.de/install/

VPNs - I've been comparing WireGuard and VpnCloud and so far like what I see with VpnCloud

Before reading the rest of this please note that I like WireGuard alot myself but I have also found VpnCloud to be very capable too.

Anyway, its a bit hard to be _apples to apples_ with the following Performance Statistics because the WireGuard Performance data I've found on its website (https://www.wireguard.com/performance/) _does not include enough test criteria information compared to what VpnCloud provided_ (https://vpncloud.ddswd.de/features/performance/).

For instance:

_For the iPerf tests VpnCloud includes results for various MTU sizes whereas WireGuard's test doesn't say what their Tested MTU was?_

The PING Tests for VpnCloud indicates various Ping Packet Sizes and stats _but the WireGuard  Ping Test does not indicate what Packet size they used._

Overall I think if you look at performance (ie iPerf) & latency for VpnCloud & WireGuard that VpnCloud compares well...

Encrypted VpnCloud (ChaCha20, MTU 7000) 938 Mbps compared to 1011 Mbps for WireGuard

That VpnCloud is 93% of the WireGuard rate quoted (both using 256 bit ChaCha20 encryption)

**WireGuard**: https://www.wireguard.com/performance/

**VpnCloud**:   https://vpncloud.ddswd.de/features/performance/

Also, regarding WireGuard's higher performance difference over VpnCloud...  I think some of the performance difference was due to:

- VpnCloud tests were done using a Intel Core i5-2540M CPU @ 2.60GH and Intel Core i5-3450 CPU @ 3.10GHz
- WireGuard tests say they used Intel Core i7-3820QM and Intel Core i7-5200U.

I've configured both WireGuard and VpnCloud and my .02cents so far is that VpnCloud is the easier/quicker to configure!

My trial of both used servers on AWS (east US), Hetzner Cloud (Germany) and a server at my home.

Here was a good writeup of VpnCloud:

[How to set up a peer-to-peer fully-meshed VPN between servers](https://medium.com/@matteocontrini/how-to-setup-a-peer-to-peer-fully-meshed-vpn-between-servers-249a9071e714)

VpnCloud features:

-  Setting up tunnels between two networks via Ethernet (TAP) and IP (TUN)
-  Connecting multiple networks with multiple forwarding behaviors (Hub, Switch, Router)
-  Encrypted connections
-  Automatic peer-to-peer meshing, no central servers
-  NAT and (limited) firewall traversal using hole punching
-  Automatic reconnecting when connections are lost
-  Non-native forwarding modes, e.g. IP based learning switch and prefix routed Ethernet networks.
-  High throughput and low additional latency (see [Performance page](https://vpncloud.ddswd.de/features/performance/))
-  Support for tunneled VLans (TAP device)
-  Option to hide protocol header
-  Automatic port forwarding via UPnP

**Comment by pirate** [comment]
Added in https://github.com/pirate/wireguard-docs/commit/b0d447ad66bb447fe0c793c010e91870f928823e
