### ISSUE TITLE
Some typos (but not in the code snippets)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pirate/wireguard-docs#3]
> ability to easily create a LAN like 10.0.0.0/24 between all my servers, every peer can connect to every peer,

The other list items are not followed by commas.

> It's also the fast as hell.

Should be, 'It's also fast as hell.'

> (Windows/Android not needed but would be nice

Missing closing parenthesis.

**Comment by POTATOES-BoilEm-MashEm-StickEm-inAStew** [comment]
> ZeroTier: haven't tried it yet, sould I?

Should be: Haven't tried it, **should** I?

**Comment by pirate** [comment]
Fixed in https://docs.sweeting.me/s/wireguard, will update the GitHub version shortly.
