### ISSUE TITLE
Fix OpenVPN Error

### ISSUE THREAD

**Issue by hyperxpro** [pirate/wireguard-docs#31]
On Readme, I found: OpenVPN: stealthy because it looks like HTTPS traffic, but it does TCP-over-TCP (👎).

Well, OpenVPN supports TCP as well as UDP at the tunnel transport layer. So your "TCP-over-TCP" is wrong. Fix it.

**Comment by StephenBrown2** [comment]
> Fix it, **please?**

FTFY

**Comment by pirate** [comment]
https://github.com/pirate/wireguard-docs/commit/9c3d5dab5a6fdf4d7b6b86f83b6a8a4ddaceee6a
