### ISSUE TITLE
Isolated subnets for each peer 

### ISSUE THREAD

**Issue by GiannisRallis** [pirate/wireguard-docs#33]
Hello, i want to create a wireguard server for some clients only for internet access but i want to isolate them from each other. I don't want to ping each other or discovered. I used iptables but no result. Can anyone help me?

**Comment by olafrv** [comment]
Give this a try: Since wireguard can run in a docker container per user, to have one interface per user?.

**Comment by olafrv** [comment]
> Hello, i want to create a wireguard server for some clients only for internet access but i want to isolate them from each other. I don't want to ping each other or discovered. I used iptables but no result. Can anyone help me?

Give this a try: Since wireguard can run in a docker container per user, to have one interface per user?.

**Comment by pirate** [comment]
I don't think docker is solving the specific issue that @GiannisRallis is asking about, though it might not be a bad tangent to investigate for other reasons.

I think what you're looking for can be accomplished with a single wireguard instance (no need for separate docker containers) by giving each client its own subnet, and not adding the IPtables rules to forward between the different subnets on any relay servers.

**Comment by pirate** [comment]
Just talked to Jason and he said this is actually doable without needing separate interfaces by using the `iptables` `FORWARDING` table to restrict traffic to only allow Wireguard <-> Ethernet forwarding and not Wireguard <-> Wireguard.

**Comment by KvizadSaderah** [comment]
> Just talked to Jason and he said this is actually doable without needing separate interfaces by using the `iptables` `FORWARDING` table to restrict traffic to only allow Wireguard <-> Ethernet forwarding and not Wireguard <-> Wireguard.

but how? >_>
