### ISSUE TITLE
Wireguard GUI & management ?

### ISSUE THREAD

**Issue by gurabli** [pirate/wireguard-docs#36]
Hi,
Is there a good, maintained and reliable script or project that I could use to manage Wireguard and peers on self hosted browser based GUI? 
Like creating keys, config files, adding peers, and configuring routes to peers (like does the client have access to whole remote LAN or not, etc). 

Which one would you recommend, if any?

**Comment by StephenBrown2** [comment]
You might check out [Algo](https://github.com/trailofbits/algo).

**Comment by andofrjando** [comment]
I was looking for the same thing and found this one that looks promising. Haven't tested it just yet. https://github.com/vx3r/wg-gen-web

**Comment by pirate** [comment]
Yeah there are a bunch listed here: https://github.com/pirate/wireguard-docs#wireguard-setup-tools

Tailscale is probably the best if you're ok with something commercial: http://tailscale.com/ otherwise I'd recommend Algo.
