### ISSUE TITLE
how multi user use a config file

### ISSUE THREAD

**Issue by karimi12** [pirate/wireguard-docs#49]
hi 
in openvpn multi user can use a certificate file for connect to server 
in wireguard  multi user can use a file?

**Comment by pirate** [comment]
You cannot have peers share the same keys, a new key must be generated for each client.

However, once you generate those keys, all the peers can be stored in a single file that all the clients share, see: https://github.com/pirate/wireguard-docs#sharing-a-single-peersconf-file
