### ISSUE TITLE
Remove keys from repository to prevent usage

### ISSUE THREAD

**Issue by Zocker1999NET** [pirate/wireguard-docs#50]
I'm sure you know that the keys you have published are not secure anymore. However the examples look like `copy/paste/work` files, which they are **except** for the keys. People just learning how to use unix/wireguard/… might see your repository, overfly the manual, copy the examples as required and then it works. Then they won't think again about security if setting up a running WireGuard VPN was their primary goal! So please remove the keys, add a README with a big warning sign to these examples or replace the key data with something like `<YOUR PRIVATE KEY, see README>`.

**Comment by pirate** [comment]
The keys are intentionally all broken for this reason, if you try running the configs by straight copy/pasting it won't connect 😉 , which should force people to regenerate their own keys.

If you find a case where this isn't true feel free to comment back and I'll reopen this.
