### ISSUE TITLE
Add Drago to the list of setup tools/related projects

### ISSUE THREAD

**Issue by edufschmidt** [pirate/wireguard-docs#55]
Drago is a tool for dynamically configuring Wireguard overlays. It follows a client-server paradigm, in which a centralized server provides multiple clients running alongside WireGuard with their desired state. In addition, the server also exposes an API and serves a slick UI for monitoring and configuring networks, hosts, interfaces, and links.

https://github.com/seashell/drago

**Comment by pirate** [comment]
Wow this one is awesome, one of the better Wireguard GUIs I've seen to date.  Will be following it closely for updates :)

https://github.com/pirate/wireguard-docs/commit/64b98cb2fafaaf3ed1da77f6a6673e9fd6dba15b
