### ISSUE TITLE
YAST: Wireguard Setup Tools

### ISSUE THREAD

**Issue by psyhomb** [pirate/wireguard-docs#57]
First of all I'd like to thank you all for creating such extensive documentation about WireGuard!

Could you please also add [this tool](https://github.com/psyhomb/wireguard-tools) to the list of [Wireguard Setup Tools](https://github.com/pirate/wireguard-docs#wireguard-setup-tools). :wink: 

Thank you very much.

**Comment by psyhomb** [comment]
:confused:

**Comment by pirate** [comment]
if you open a PR I'll accept it

**Comment by psyhomb** [comment]
Thank you! :slightly_smiling_face:
