### ISSUE TITLE
Why use /32 instead of /24 for a client's [Interface]?

### ISSUE THREAD

**Issue by martinsstuff** [pirate/wireguard-docs#73]
https://github.com/pirate/wireguard-docs#QuickStart (Step 4.)

I tried looking into it but so far couldn't find a definitive answer, from what I can tell from testing, both /32 and /24 seem to work mostly the same, except that the netmask obviously is different (for example 255.255.255.255 vs 255.255.255.0). So the choice to use /32 seems weird to me as it would (from my understanding) mean that any traffic would come from outside the client's own subnet.

I understand why one would use /32 in the **AllowedIPs** for a peer (to prevent peer's netmasks overlapping) but I don't understand why use it in a client's [Interface] config.

Looking at the various guides and documentations from reputable sources there doesn't seem to be a consensus and both /32 or /24 are being used in examples.

Edit: Examples:

## /24:

https://www.digitalocean.com/community/tutorials/how-to-set-up-wireguard-on-ubuntu-20-04

https://wiki.debian.org/SimplePrivateTunnelVPNWithWireGuard

The Quick Start video on the **official WireGuard website**: https://www.wireguard.com/quickstart/

## /32:
https://docs.opnsense.org/manual/how-tos/wireguard-client.html (mentions matching client's [Interface] to server's `AllowedIPs`)

https://upcloud.com/community/tutorials/get-started-wireguard-vpn/

https://www.thomas-krenn.com/en/wiki/Ubuntu_Desktop_as_WireGuard_VPN_client_configuration

**Comment by gtrabanco** [comment]
In the server when you are using /32 you also configuring a route for specific ip address through that peer. It is a routing concept.

For example you have route to network /24 through one link A but any specific IP is reachable through other route, you should specify a static route with the ip with CIDR /32 through whatever route is necessary to take.

**Comment by martinsstuff** [comment]
> In the server when you are using /32 you also configuring a route for specific ip address through that peer. It is a routing concept.
> 
> For example you have route to network /24 through one link A but any specific IP is reachable through other route, you should specify a static route with the ip with CIDR /32 through whatever route is necessary to take.

Isn't that `AllowedIPs` stuff?

So from your example

```
[Peer]
#Peer 1 - Entire Subnet
AllowedIPs = 10.0.0.0/24
[Peer]
#Peer 2 - Just one IP
AllowedIPs = 10.0.0.2/32
```

**Comment by gtrabanco** [comment]
Yes

**Comment by pirate** [comment]
They serve different purposes @gtrabanco, `/24` = route all traffic to the rest of the subnet through this node, `/32` = only route traffic destined for that specific node to that node.
