### ISSUE TITLE
Update client list.

### ISSUE THREAD

**Issue by UrielCh** [pirate/wireguard-docs#76]
Hi,

please consider updating your manage key section, [https://wirt.network/](https://wirt.network/) does not exist anymore.

And you may add my wireguard Keys / config manager:

[https://github.com/UrielCh/wireguard](https://github.com/UrielCh/wireguard)

My version is a bit like [https://github.com/its0x08/wg-install](https://github.com/its0x08/wg-install), but have no interactive mode, and it is optimized to handle a lot of keys.

This is my third version of the script, the second one was for Tinc VPN, and the first for OpenVPN.

**Comment by pirate** [comment]
https://github.com/pirate/wireguard-docs/commit/9015e77c3a5a97cdaed1238f80da2a1a3ff81bfe
