### ISSUE TITLE
external IP forward 

### ISSUE THREAD

**Issue by lootoos** [pirate/wireguard-docs#79]
how to configure iproute2 + iptables?

**Comment by pirate** [comment]
Need to know more about your setup. Who and where is the "player", what is the config you're using, what are you trying to accomplish, etc.

**Comment by lootoos** [comment]
how do I configure Iptables to forward?

**Comment by pirate** [comment]
It depends on what you're trying to forward and how, need a lot more info about your setup and what you're trying to accomplish if you want help.
