### ISSUE TITLE
How to configure Docker's NAT?

### ISSUE THREAD

**Issue by lootoos** [pirate/wireguard-docs#84]
![photo_2022-12-22_18-53-14](https://user-images.githubusercontent.com/109325265/209172474-c133f643-1cc4-46f6-9feb-2a3dfcf41ac9.jpg)
How do I configure this to log in to the server? If the rules are removed via iptables -t nat -F - then the server enters but the Ip of the players is "172.18.0.1"

**Comment by pirate** [comment]
This is like asking a mechanic "how do I make my engine work" and saying you have a Ford car with no other information. We need *a lot* more information to provide any help. What are you trying to accomplish, what is the network layout, what OS/package versions are you using, which server is trying to connect using what command, etc...
